volumes:
  db:
  phpmyadmin:


networks:
  bymr:


services:
  web:
    build: ./server
    environment:
      - BASE_URL=localhost
      - PORT=3001
      - DB_NAME=bymr
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=bymr
      - DB_PASSWORD=bymr
    networks:
      - bymr
    ports:
      - 3001:3001
    depends_on:
      - db
  db:
    image: mariadb:lts
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=bymr
      - MARIADB_PASSWORD=bymr
      - MARIADB_DATABASE=bymr
    ports:
      - 3306:3306
    networks:
      - bymr
    volumes:
      - db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=db
    ports:
      - 8080:80
    networks:
      - bymr
    depends_on:
      - db
